# Generated by Django 4.1.6 on 2023-03-10 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active_status',
            field=models.BooleanField(default=False, verbose_name='Тестування активно'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата закінчення'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата початку'),
        ),
    ]
