# Generated by Django 4.1.6 on 2023-03-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_active_status_exam_end_date_exam_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='active_status',
            new_name='is_active',
        ),
    ]
