# Generated by Django 4.1.6 on 2023-03-10 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_active_status_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата початку'),
        ),
    ]
