# Generated by Django 4.1.6 on 2023-03-10 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exam_end_date_alter_exam_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата початку'),
        ),
    ]
