# Generated by Django 4.1.6 on 2023-03-10 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exam_end_date_alter_exam_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
