# Generated by Django 4.1.6 on 2023-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditionaluserinfo',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
