# Generated by Django 4.1.7 on 2023-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_question_answer_remove_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersexam',
            name='exan_pk',
            field=models.IntegerField(null=True, verbose_name='ID Екзамену'),
        ),
    ]
