# Generated by Django 4.1.7 on 2023-03-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usersexam_exan_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersexam',
            old_name='exan_pk',
            new_name='exam_pk',
        ),
    ]
