# Generated by Django 4.1.7 on 2023-03-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_exan_pk_usersexam_exam_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrectanswers',
            name='exam_pk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
            preserve_default=False,
        ),
    ]
