# Generated by Django 4.1.7 on 2023-03-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_incorrectanswers_exam_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectanswers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
