# Generated by Django 4.1.7 on 2023-03-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_incorrectanswers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectanswers',
            name='exam_pk',
        ),
        migrations.AlterField(
            model_name='incorrectanswers',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
    ]
