# Generated by Django 4.1.7 on 2023-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_incorrectanswers_exam_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
