# Generated by Django 4.1.7 on 2023-03-20 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_incorrectanswers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersexam',
            name='exam_pk',
        ),
        migrations.AlterField(
            model_name='usersexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
        ),
        migrations.AlterField(
            model_name='usersexam',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
