# Generated by Django 4.1.7 on 2023-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_usersexam_exam_pk_alter_usersexam_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditionaluserinfo',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
