# Generated by Django 4.1.7 on 2023-03-28 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_aditionaluserinfo_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersexam')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
