# Generated by Django 4.1.7 on 2023-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_examsrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersexam',
            name='retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='examsrequests',
            unique_together={('username', 'user_exam')},
        ),
    ]
