# Generated by Django 4.1.7 on 2023-04-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_usersexam_retake_alter_examsrequests_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsrequests',
            unique_together=set(),
        ),
    ]
