# Generated by Django 4.1.7 on 2023-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_examsrequests_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
