# Generated by Django 4.1.7 on 2023-05-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_messages_messagestranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagestranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagestranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='MessagesTranslation',
        ),
    ]
