# Generated by Django 4.1.7 on 2023-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_messages_messagestranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='MessagesTranslation',
            new_name='MessageTranslation',
        ),
        migrations.AlterModelOptions(
            name='messagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'message Translation'},
        ),
        migrations.AlterModelTable(
            name='messagetranslation',
            table='main_message_translation',
        ),
    ]
