# Generated by Django 4.1.7 on 2023-06-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='exam',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message'),
        ),
    ]
