# Generated by Django 4.1.7 on 2023-08-07 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_notification_exam_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsrequests',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
